### ISSUE TITLE
GenericWork should have #generic_file_ids method

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/hydra-works#87]
```
     NoMethodError:
       undefined method `generic_file_ids' for #<GenericWork:0x007fbc1b9932c8>
     # /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activemodel-4.2.1/lib/active_model/attribute_methods.rb:433:in `method_missing'
     # ./spec/actors/curation_concern/generic_work_actor_spec.rb:59:in `block (6 levels) in <top (required)>'
```

Blocks https://github.com/projecthydra-labs/hydra-works/issues/60

**Comment by flyingzumwalt** [comment]
== Clarification

ActiveModel Assocations support a *_ids method that allows you to get the ids of associated objects rather than retrieving the objects themselves.   `generic_files` is just a wrapper around `.members`, so there currently isn't a .generic_file_ids method.  Downstream code is likely to want to use that method.

We checked Sufia and found that it does not currently use the generic_file_ids method, so this is not urgent for the Sufia PCDM sprint.

**Comment by flyingzumwalt** [comment]
Question: does `.member_ids` work?
