### ISSUE TITLE
Move Derivative generation from Sufia to Hydra::Works

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/hydra-works#90]
Move Sufia::GenericFile::Derivatives to Hydra::Works::File::Derivatives

**Comment by awead** [comment]
This was accomplished in #105, but modified slightly. Sufia's current derivative generation will modify the original file and change it to a different format and save it to the object. These were removed since it would require different and cusomized file types. Only thumbnail generation is retained.
